version: '3.8'

services:
  # Base de datos PostgreSQL para Redmine
  redmine-db:
    image: postgres:15-alpine
    container_name: redmine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-redmine_password_2024}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - redmine_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - redmine-network
    ports:
      - "5433:5432"  # Puerto diferente para no conflictar con otras DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redmine -d redmine"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicaci贸n Redmine
  redmine:
    image: redmine:5.1-alpine
    container_name: redmine-app
    restart: unless-stopped
    depends_on:
      redmine-db:
        condition: service_healthy
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD:-redmine_password_2024}
      REDMINE_DB_ENCODING: utf8
      
      # Configuraci贸n de email (opcional)
      REDMINE_EMAIL_DELIVERY_METHOD: ${EMAIL_DELIVERY_METHOD:-}
      REDMINE_SMTP_ADDRESS: ${SMTP_ADDRESS:-}
      REDMINE_SMTP_PORT: ${SMTP_PORT:-}
      REDMINE_SMTP_DOMAIN: ${SMTP_DOMAIN:-}
      REDMINE_SMTP_USERNAME: ${SMTP_USERNAME:-}
      REDMINE_SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      REDMINE_SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION:-}
      REDMINE_SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_STARTTLS:-}
      
      # Configuraci贸n adicional
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY:-redmine_secret_key_2024_very_long_and_secure}
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_logs:/usr/src/redmine/log
      - redmine_plugins:/usr/src/redmine/plugins
      - redmine_themes:/usr/src/redmine/public/themes
      - ./config:/usr/src/redmine/config/docker
      - ./plugins:/usr/src/redmine/plugins/custom
    networks:
      - redmine-network
    ports:
      - "${REDMINE_PORT:-5000}:3000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx como proxy reverso (opcional para producci贸n)
  nginx:
    image: nginx:alpine
    container_name: redmine-nginx
    restart: unless-stopped
    depends_on:
      - redmine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - redmine-network
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    profiles:
      - production

volumes:
  redmine_db_data:
    driver: local
  redmine_files:
    driver: local
  redmine_logs:
    driver: local
  redmine_plugins:
    driver: local
  redmine_themes:
    driver: local

networks:
  redmine-network:
    driver: bridge 